# Generated by Django 5.2 on 2025-05-07 11:50

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_image_path),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_image_path),
        ),
    ]
